[book]
author = "sitandr"
language = "ko"
multilingual = false
src = "src"
title = "Typst 예시 북"

[preprocessor.typst-highlight]
#disable_inline = true
typst_default = true
render = true
warn_not_specified = true
prelude = "#set text(font: (\"Noto Sans CJK KR\", \"Fira Math\"))"
fonts_path = ["src/fonts"]

[output.html]
additional-css = ["./theme/mdbook-pagetoc/style.css"]
additional-js = ["./theme/mdbook-pagetoc/sidebar.js", "./theme/popup/popup.js"]
git-repository-url = "https://github.com/sitandr/typst-examples-book"

[output.html.redirect]
"/snippets/hidding.html" = "./hiding.html"
